### ISSUE TITLE
Error on Sharing The Output As ArcGIS Runtime content

### ISSUE THREAD

**Issue by BeClevest** [Esri/street-data-processing-tools#10]
Using the latest version of tool (10.4.1.1) on top of ArcGIS 10.4.1 we were able to process the street data from HERE NAVSTREETS but when trying to share the Map (which contains the output network) we are getting following errors:

------------------------------------------------------------------------------------------------------
> — High Unresolved 00190 The field [KingpinToRearAxleLengthLimit_Meters] on the table [RestrictedTurns] is greater than 31 characters in length. Routing_ND Layer Layers 
> — High Unresolved 00190 The field [SemiOrTractorWOneOrMoreTrailersProhibited] on the table [RestrictedTurns] is greater than 31 characters in length. Routing_ND Layer  Layers 
> — High Unresolved 00190 The field [TF_KingpinToRearAxleLengthLimit_Meters] on the table [Streets] is greater than 31 characters in length. Routing_ND Layer  Layers 
> — High Unresolved 00190 The field [FT_KingpinToRearAxleLengthLimit_Meters] on the table [Streets] is greater than 31 characters in length. Routing_ND Layer  Layers 
> — High Unresolved 00190 The field [TF_SemiOrTractorWOneOrMoreTrailersProhibited] on the table [Streets] is greater than 31 characters in length. Routing_ND Layer  Layers 
> — High Unresolved 00190 The field [FT_SemiOrTractorWOneOrMoreTrailersProhibited] on the table [Streets] is greater than 31 characters in length. Routing_ND Layer  Layers 
> — High Unresolved 00190 The field [TF_ExplosiveAndFlammableProhibited] on the table [Streets] is greater than 31 characters in length. Routing_ND Layer  Layers 
> — High Unresolved 00190 The field [FT_ExplosiveAndFlammableProhibited] on the table [Streets] is greater than 31 characters in length. Routing_ND Layer  Layers 
------------------------------------------------------------------------------------------------------

![runtime](https://cloud.githubusercontent.com/assets/19611313/21399226/ac560246-c75f-11e6-8ce8-6866c4feb986.png)

There is also "The network dataset has not been dissolved" warning 

------------------------------------------------------------------------------------------------------
> Medium Unresolved 10058 The network dataset has not been dissolved. Routing_ND Layer Layers 
------------------------------------------------------------------------------------------------------

can you please let me know what are theses error for?

**Comment by BeClevest** [comment]
Please ignore this issue?
This Post can be dismissed and closed as updating following Fields names fixed the problem of sharing network as ArcGIS Runtime content

KingpinToRearAxleLengthLimit_Meters = kToRearAxLimit_Meters
SemiOrTractorWOneOrMoreTrailersProhibited = semOrTraconeorProhibited
ExplosiveAndFlammableProhibited = ExploAndFlamProhibited

Thanks

**Comment by aHatakeyama** [comment]
Closing this Issue, as requested by the Issue author.
