### ISSUE TITLE
Use of NAVTEQ Traffic Patterns data - 60-minute granular 

### ISSUE THREAD

**Issue by Matteu18** [Esri/street-data-processing-tools#19]
Hello,

Thank you very much for your very useful tool.

With NAVTEQ Traffic Patterns data, the tool only makes use of the 15-minute granular Speed Patterns Dictionary (SPD) .csv file in KPH.

Do you expect to produce soon a code for 60-minute granular ? It will be very useful too.

Thank you very much for your response.

Kind regards,
Matteu

**Comment by aHatakeyama** [comment]
There are no plans to use the 60-minute granular SPD, since the 15-minute granular SPD is able to provide greater detail.  If using the 60-minute granular SPD is desired, the tool's source code is public, so you can modify the source code to be able to consume the 60-minute granular SPD.
