### ISSUE TITLE
Add checkbox for build network

### ISSUE THREAD

**Issue by nicogis** [Esri/street-data-processing-tools#23]
In the tool give the user option **'build network'** .
It is possible in fact that the user wants to add / modify their own restrictions or other before making the final build. For large dataset the build is long so user can run build only once

**Comment by mmorang** [comment]
This was addressed in https://github.com/Esri/street-data-processing-tools/pull/45. This checkbox has been added to the ArcMap version of the tool and the new ArcGIS Pro version.

**Comment by nicogis** [comment]
Ok, thanks
