### ISSUE TITLE
Processing TomTom data with multiple input MN Input files

### ISSUE THREAD

**Issue by scm75265** [Esri/street-data-processing-tools#26]
I am using the “Street Data Processing Tools 10.6.0.2” which I downloaded from this site.

In the case of South Africa, we have 6 regions which need to be consolidated to build a national data-set.  When I run the process on an individual region using the following files I do not have any problems and it works well and gives accurate results:

1.	Shapefiles - NW, MN
2.	Tables - RS, SI, SP, MP
3.	Speed Profiles – HSNP, NSPR

When I merge (shapefiles) and append (tables) the six individual files together to create a national dataset, the basic shortest distance, fastest routing works, however when enabling time windows (using the speed profile information), the answers are not accurate and its give strange results.

What is the correct approach to consolidate the individual MN files to build a street network as you cannot merge multiple “built” street networks?  Any advice in this regard will be greatly appreciated.

**Comment by aHatakeyama** [comment]
@scm75265,
When you're combining the tables, are you merging the six HSPR tables together?  This is the one table that you're NOT supposed to merge together (all others you do merge) -- see the following excerpt from the tool's Help button:
> Multiple regions of Tele Atlas MultiNet data can be processed together to create a larger network dataset. First use the Merge tool to combine the similar layers of the MultiNet data into common feature classes and tables, then pass these combined feature classes and tables as inputs to this tool. Do not combine the Historical Speed Profiles (HSPR) tables from the various regions, as this table is identical in all regions within the same continent.

**Comment by scm75265** [comment]
Thank you for the feedback, I will process accordingly.
