### ISSUE TITLE
Merged Network from Here NavStreets issue

### ISSUE THREAD

**Issue by gcontino** [Esri/street-data-processing-tools#27]
I'm using HERE Navstreets for Italy and I need to merge the 5 areas into one built network.
I merged all required shapefiles/tables (Streets, AltStreets, Z-Levels, CDMS, etc) in a geodb.
I processed them by the tool after merging them but the process returned me a lot of errors (Cannot find links...).
The entire network was created anyway, but it isn't routable at all, because it gives me errors of positioning of stops, errors of restrictions (soft anf hard), and so on.
I will appreciate your contributions.
Thanks,
Gianni

**Comment by xeir83** [comment]
Been there, done that. :)
You might already have fixed this, but... 
If you are using pythonscript to extract the tar files, make sure you don't extract them to the same directory - you will then overwrite your other extracted files and the streets, altstreets (and so on) will mismatch. 
Therefore, extract the files into separate directorys and then merge them into your gdb.

**Comment by mmorang** [comment]
I apologize that we never responded to this question.  Did you ever find a solution, or do you still need help with this workflow?

**Comment by mmorang** [comment]
It's been three months, and there has been no response on this issue, so I'm closing it.  If you're still having problems, feel free to re-open.
