### ISSUE TITLE
10.6.02 Failing Build GPPRocessVendorDataFunctions

### ISSUE THREAD

**Issue by chritomix** [Esri/street-data-processing-tools#31]
Hi, I am using VS community 2015, arcigs 10.6.1. When trying to Build GPProcessVendorDataFunctions, it shows me the error  within  "ProcessMultiNetDataFunction.cs' line 3411: 
calcFieldTool = new CalculateField();
The error says:  _the name calcfieldtool does not exist in the current context_.
Solution - I have modified that line with new variable: CalculateField calcFieldTool2 = new CalculateField(); and i used calcfieldtool2 to run following field calculation

**Comment by mmorang** [comment]
It seems like this user identified a bug in the code and fixed it, and my colleague installed a fix into the tool code back in 2019.  Closing this issue as completed.
