### ISSUE TITLE
HERE routing network ignores some prohibitions

### ISSUE THREAD

**Issue by kn815dt** [Esri/street-data-processing-tools#35]
Our HERE data routing network is having a couple of strange problems:

1)	When we alter the restriction that is applied to “Avoid Unpaved Roads”, the resultant route responds appropriately.
2)     When we alter the restriction that is applied to “Through Traffic Prohibited”, the resultant route responds appropriately.	
3)     When we alter the restriction that is applied to “Avoid Private Roads”, the resultant route ignores the restriction.
4)	When we alter the restriction that is applied to “Avoid Gates”, the resultant route ignores the restriction.

Why do some of the categories seem to not work?

**Comment by mmorang** [comment]
I apologize that we never responded to this question.

There doesn't seem to be enough information here for me to fully understand or answer the question.  What do you mean by "alter the restriction"?  Do you still need help with this problem?

**Comment by mmorang** [comment]
It's been three months, and there has been no response on this issue, so I'm closing it.  If you're still having problems, feel free to re-open.
