### ISSUE TITLE
The tools do not work with ArcGIS Desktop 10.4 and 10.4.1 

### ISSUE THREAD

**Issue by deelesh** [Esri/street-data-processing-tools#4]
The tools do not work with ArcGIS Desktop 10.4 and 10.4.1. The Process NAVSTREETS Street Data tool fails with an error **Field named COND_TYPE is not the expected type** for `Input Condition/Driving Manoeuvres (CDMS) Table` parameter.

**Comment by behClevest** [comment]
We also have same issue with the tool on ArcGIS 10.4. I update the **COND_TYPE** data format to **Short** in  **CDMS.dbf** and the tool didn't complain about the type but now we are getting error on `starting "Creating ans building the network dataset....`

`<Error>Exception from HRESULT: 0x800422F8</Error>
<Error>   at ESRI.ArcGIS.Geodatabase.IDatasetContainer2.CreateDataset(IDEDataset DataElement)  at GPProcessVendorDataFunctions.ProcessNavStreetsDataFunction.CreateAndBuildNetworkDataset(String outputFileGdbPath, Double fgdbVersion, String fdsName, String ndsName, Boolean createNetworkAttributesInMetric, Boolean createArcGISOnlineNetworkAttributes, String timeZoneIDBaseFieldName, Boolean directedTimeZoneIDFields, String commonTimeZone, Boolean usesHistoricalTraffic, ITrafficFeedLocation trafficFeedLocation, Boolean usesTransport) in e:\Tools\StreetDataProcessingTools\ProcessNavStreetsDataFunction.cs:line 6992

   at GPProcessVendorDataFunctions.ProcessNavStreetsDataFunction.Execute(IArray paramvalues, ITrackCancel trackcancel, IGPEnvironmentManager envMgr, IGPMessages messages) in e:\Tools\StreetDataProcessingTools\ProcessNavStreetsDataFunction.cs:line 3143</Error>

<Error>Failed to execute (ProcessNavStreetsData).</Error>
</Error>`

**Comment by chiubaca** [comment]
Getting the same problem as @deelesh. Is it working ok on older versions of ArcMap?

**Comment by nealjohnston** [comment]
Yes this tool to convert TomTom's MultiNet does not work with 10.4 or 10.4.1, only versions lower than this. There has however been work done by Interpret Geospatial Solutions on making an ESRI network from the new MultiNet-R dataset by TomTom. But currently MultiNet will still need to be processed on earlier versions of ArcGIS.

**Comment by aHatakeyama** [comment]
The latest release (10.4.1.1) works with ArcGIS 10.4.1.
