### ISSUE TITLE
SEQNR not the Expected Type TomTomMultinet 10.8.0.1 tool with ArcMap 10.8.1

### ISSUE THREAD

**Issue by gregmiddleton** [Esri/street-data-processing-tools#42]
ArcMap 10.8.1 with tool 10.8.0.1
TomTom source data is file gdb format native download from TomTOm
When populating the table locations, I'm getting multiple SEQNR is not the expected type.

![image](https://user-images.githubusercontent.com/973041/125227237-59346380-e287-11eb-8f69-be63860fc735.png)

The SEQNR fields are showing as Type Short in properties

![image](https://user-images.githubusercontent.com/973041/125227326-8f71e300-e287-11eb-820e-91800d64f6a6.png)

**Comment by mmorang** [comment]
I apologize that we never responded to this question. It seems that these mismatching field type errors were quite common, and there are several other similar issues logged by other users. I'm not sure whether it's still an issue.

A new version of the Street Data Processing Tools for ArcGIS Pro is now available. If you're still processing TomTom data, please try the new version of the tool and let us know if you're still experiencing problems with field type checks failing. We may be able to address it more easily in the new version of the tool.
