### ISSUE TITLE
Process MultiNet Time Zones will not run - Field TollRd incorrect type

### ISSUE THREAD

**Issue by gregmiddleton** [Esri/street-data-processing-tools#43]
Arcmap 10.8.1
Street Processing Tools 10.8.0.1

When attempting to use the tool for Process MultiNetTimeZones, the tool is unable to run after selecting the NW network Geometry.  The tool reports error -1 Field name TOLLRD is not the expected type.  I tried using both a shpd download from TomTom and a FGDB download from ESRI.

ArcMap Properties for the feature class shows TOLLRD as type Short Integer.

![image](https://user-images.githubusercontent.com/973041/125689126-01fe327e-7452-49f7-a950-c7fabdc298c5.png)

**Comment by mmorang** [comment]
This was fixed in https://github.com/Esri/street-data-processing-tools/pull/45 and is available in the latest release of the ArcMap version of this tool.  Please let us know if it doesn't resolve your issue.
