### ISSUE TITLE
Error messages with Pro version of the tool I don't get with the ArcMap version

### ISSUE THREAD

**Issue by geraldine0** [Esri/street-data-processing-tools#46]
I get a number of warnings when running the Pro tool with TomTom data, while the ArcMap tool runs smoothly:

_There were no records in the maneuver path table for ID 10561086890487.0, which appears in the maneuver geometry feature class._ (for about 35000 records)

_There were too many records in the sign info table for ID 10561001105482.0, which appears in the sign path table. The signpost (ObjectID 10) will be truncated._ (for about 30 records)

My questions: 
1. Are there new checks performed in the Pro version compared to the ArcMap version? Is this also happening somehow with the ArcMap version behind the scenes, without message returned? 
2. Or is there a problem with the data? What the message says is true, the mentioned records are missing.
3. Is the network usable anyway?

I'm using Pro 2.9.2. and the last version of TomTom for Belgium.

Thanks for any help

**Comment by mmorang** [comment]
Hello @geraldine0.  Sorry for the delay in response.

Yes, the new Pro version does more thorough data checking and problem reporting than the old ArcMap tool.  So, with the same data, you may see warnings in Pro that you did not see in ArcMap.

I think it's likely that the data is okay to use, but I refer that part of the question to my colleague @aHatakeyama.  Alan, if that situation is common, perhaps we should consider suppressing that warning, or at least not throwing 35,000 copies of it.

**Comment by aHatakeyama** [comment]
Hi @geraldine0.  Apologies for the delay in my response.

Is it possible that the MP layer isn't properly combined to include both tiles of Belgium prior to you running the tool?  Maneuver ID 10561086890487 is located in the "be3" tile of the MultiNet data.  The 2024.06 MultiNet release has about 41400 maneuvers in the "be3" tile, while the 2022.06 MultiNet release has about 40400 maneuvers in the "be3" tile.  I'm not sure what release you were using back then, so the 35000 errors probably cover the entire "be3" tile of Belgium for your data.

**Comment by mmorang** [comment]
It's been three months, and there have been no further comments on this issue, so I'm closing it.  If you're still having problems, feel free to re-open.
