### ISSUE TITLE
HERE data processing tool fails due to Spatial Index issue with Signposts Feature Class

### ISSUE THREAD

**Issue by sirri050** [Esri/street-data-processing-tools#49]
After resolving the Link_ID field issue as well as some other fields that are having incorrect types, the HERE Data Processing Tool runs, but fails as shown here:

42696 of 42702 signposts added.
Executing: AddSpatialIndex E:\NAVSTREETS_PRJ1\CESTREETS.gdb\Routing\Signposts 0 0 0
Start Time: Sat Nov 12 04:18:25 2022
ERROR 999999: Error executing function.
The spatial index grid size is invalid. [Signposts]
The spatial index grid size is invalid.
Failed to execute (AddSpatialIndex).
Failed at Sat Nov 12 04:18:26 2022 (Elapsed Time: 0.94 seconds)
Executing: AddSpatialIndex E:\NAVSTREETS_PRJ1\CESTREETS.gdb\Routing\Signposts 0 0 0
Start Time: Sat Nov 12 04:18:25 2022
ERROR 999999: Error executing function.
The spatial index grid size is invalid. [Signposts]
The spatial index grid size is invalid.
Failed to execute (AddSpatialIndex).
Failed at Sat Nov 12 04:18:26 2022 (Elapsed Time: 0.94 seconds)
Error HRESULT E_FAIL has been returned from a call to a COM component.
   at ESRI.ArcGIS.Geoprocessing.GeoProcessorClass.Execute(String Name, IVariantArray ipValues, ITrackCancel pTrackCancel)
   at ESRI.ArcGIS.Geoprocessor.Geoprocessor.ExecuteInner(IGPProcess process, ITrackCancel trackCancel, IGeoProcessor igp, IVariantArray iva)
   at ESRI.ArcGIS.Geoprocessor.Geoprocessor.Execute(IGPProcess process, ITrackCancel trackCancel)
   at GPProcessVendorDataFunctions.ProcessNavStreetsDataFunction.Execute(IArray paramvalues, ITrackCancel trackcancel, IGPEnvironmentManager envMgr, IGPMessages messages)
Failed to execute (ProcessNavStreetsData).
Failed at Sat Nov 12 04:18:28 2022 (Elapsed Time: 19 hours 27 minutes 0 seconds)

However, it creates a Routing dataset with streets, signposts, and restrictedTurns FCs. As a workaround, I created the Network Dataset manually, but there are still problems when creating the geocoders. Any idea how we can solve the Sptial Index issue? I tried removing and adding spatial index to the FCs in the NavStreets GDB. It didn't work.

**Comment by mmorang** [comment]
I apologize that we never responded to this question.

A new version of the Street Data Processing Tools for processing HERE data in ArcGIS Pro is now available.  If you're still processing HERE data, please try the new version of the tool and let us know if you're still experiencing problems with the spatial index.

**Comment by sirri050** [comment]
Thanks, Melinda for your response. I could manage to create the Network Dataset successfully on ArcMap, but with a lot of manual work. I believe now it will be easy to work with.
I am no longer working with the same company, but will let them know that it is now available on Pro.

**Comment by mmorang** [comment]
Okay, thank you.  I'm going to close this issue, then.  If your former colleagues experience any problems, they should log a new issue, and we will do our best to help them in a more timely manner.
