### ISSUE TITLE
Tool Not Licensed

### ISSUE THREAD

**Issue by MacGuruTx** [Esri/street-data-processing-tools#5]
I have a 10.3.1 Desktop Basic installation with Network Analyst.

After extracting, install.bat, opening Arcmap and then accesing the tools from the toolbox; 
I get a Tool Not Licensed error box.

Unable to execute the selected tool.
You no not have the necessary license to execute the selected tool.

What  licenses, extensions are required to actually use this toolbox?

**Comment by aHatakeyama** [comment]
Hi @MacGuruTx,

Can you provide more details as to how you're encountering the error?  Details such as:
- Which of the four tools is causing the error?
- What data product (NAVSTREETS or MultiNet) are you using, and which vintage/version number are you using this with?
- What region of the world is this data for?

Any other details you can provide will definitely help!  Thanks!

**Comment by aHatakeyama** [comment]
I wasn't able to find any functions used in the tools that require higher than a Basic license.  Can you also provide me with the messages returned by the failing tool so I can see which function is throwing the licensing error?  Thanks again!

**Comment by MacGuruTx** [comment]
Sure.
ArcGIS 10.3.1 for Desktop – Version 10.3.1.4959
Basic license
Network Analyst License

StreetDataProcessingToolsv10.3.1.2 downloaded today.

Process I’ve used
Street Data processing tools are in a sub folder of my documents (C:\Users\<username>\Documents\GIS\StreetDataProcessingTools_v10.3.1.2\StreetDataProcessingTools)

R/Click GPProcesVendorDataFunctions.dll
General/ Unblock
Run Installtools.bat

Open Arcmap
Go to ArcToolbox
r-click on Arctoolbox and select Add Toolbox
go through browser to C:\Users\<username>\Documents\GIS\StreetDataProcessingTools_v10.3.1.2\StreetDataProcessingTools
select Street Data Processing Tools.tbx and then Open

Select one of the tools
Ie Tomtom
Process Multinet Street data or Process NAVSTREETS Street data
I get the Tool not Licensed error

I just tried the Time Zone Data tools and these both work for HERe or TomTom


Greg Middleton
Principal Product Manager – CAD, Mobile, and GIS
TriTech Software Systems | www.tritech.com<http://www.tritech.com/>
Direct: (858) 799-7342 | Mobile 858-405-7422
Support: 1-800-987-0911  (choose option #1)

Need to schedule a mtg and don’t work for TriTech; See my public calendar on the internet here:
Greg's Calendar<https://outlook.office365.com/owa/calendar/3639e0d04cf443eca18d02a640b0ce73@tritech.com/4933564a83b849e2aac371710926f18615619763283041009414/calendar.html>

**Comment by MacGuruTx** [comment]
And to be clear, I’m getting this error message when I doubleclick to start the Process Street data tools. I never get to a dialog box to set input out put workspaces. I get the Tool not licensed error immediately before being presented with a menu.

**Comment by aHatakeyama** [comment]
You mentioned that you installed Network Analyst alongside ArcGIS, but do you have the Network Analyst extension actually turned on inside of ArcMap (click Customize > Extensions, and then click the checkbox(es))?

**Comment by MacGuruTx** [comment]
DOH!..

That is indeed the issue.  Thank you !
