### ISSUE TITLE
Oneway restriction missing for ArcGIS Pro?

### ISSUE THREAD

**Issue by ech-rho** [Esri/street-data-processing-tools#50]
Is the oneway restriction missing for ArcGIS Pro or am I missing something?

**Comment by mmorang** [comment]
The enforcement of one-way travel along streets is handled in each individual vehicle's restriction attribute.  If a street is one way for all vehicles, it should be included in the “All Vehicles Restricted” restriction attribute for the appropriate direction of travel.

**Comment by mmorang** [comment]
(I'll close the issue since I think we've answered your question, but feel free to reopen if you have further questions or identify a problem with these restrictions.)
