### ISSUE TITLE
ArcMap - Process NAVSTREETS™ Street Data (for 10.8.1) - error running python script with parameters

### ISSUE THREAD

**Issue by gisdev4git** [Esri/street-data-processing-tools#55]
I have set up the tool, and it works successfully in ArcMap when I provide all of the parameters. When I attempt to run a python script using the same parameters I get an error. 

**ProcessNavStreetsData() takes 0 positional arguments but 27 were given.** 

I am following the same code as is provided in the XML sample here: https://github.com/Esri/street-data-processing-tools/blob/master/for-ArcMap/ProcessNavStreetsData_nasample.xml

Is there something missing in how I am calling this function?

arcpy.ProcessNavStreetsData_mytoolbox(inStreets, inAltStreets, inZLevels, inCDMS, inRDMS, inSigns,
                outFileGDB, "10.1", fdName, ndName,
                inMetric, arcgisOnlineAttributes, "#", "#", inCommonTimeZone,
                inTraffic, "#", "#", inTMC, inSPD, "#", "#", "#", "#",
                inCndMod, "#", inBuild)

Thank you.

**Comment by mmorang** [comment]
I apologize that we never responded to this question.

A new version of the Street Data Processing Tools for processing HERE data in ArcGIS Pro is now available.  If you're still processing HERE data, please try the new version of the tool (which should work reliably when called via Python) and let us know if you're still experiencing problems.

**Comment by mmorang** [comment]
It's been three months, and there has been no response on this issue, so I'm closing it.  If you're still having problems, feel free to re-open.
