### ISSUE TITLE
Error when running Street tool Data Processing Tools - TomTom Data

### ISSUE THREAD

**Issue by jlasseiceira** [Esri/street-data-processing-tools#6]
I need help on an error that has been showing when I use the Street Tool Data Processing Tools (version 10.3.1.2) to process the last TomTom data for Portugal.

When using the tool Process MultiNet® Street Date (TomTom), an error is displayed in step Update by Alternate ID Fields, with the following message: The value for the Edge1End field in the turn feature class is invalid. Unfortunately it doesn’t give any further details. When testing the same tool with a version of of 2015 of TomTom data, the process has run normally, with the conclusion that the error appears to be due to the version of TomTom data after 2016_03. The Update by Alternate ID Fields tool uses only a shapefile network file (prtprt________nw) and the corresponding ID field. I was not able to identify any obvious errors in this field. All records are filled.

It would be possible to analyze the origin of this error? Is there any history of errors of this kind in Street Data Processing Tools?

**Comment by aHatakeyama** [comment]
Hi @jlasseiceira,

I haven't seen the error you mentioned.  I tried running the Process MultiNet Street Data tool against the 2016_06 MultiNet data for Portugal and it completed successfully (I first combined the prtpt2 and prtpt3 regions into combined feature classes and tables, then fed these combined feature classes and tables (nw, mn, mp, si, and sp feature classes) into the 10.4.1.1 version of the Process MultiNet Street Data tool; and the tool completed after around 20 minutes).

I noticed that you mentioned that the MultiNet data you're using is for the "prtprt" region, which seems to indicate that the entire region class covers all of Portugal.  My MultiNet data for Portugal splits it into two regions (prtpt2 and prtpt3), which required me to combine them together before processing to yield one dataset for all of Portugal.  I haven't seen the data for Portugal come delivered from TomTom all in one "prtprt" region since the 2014_06 release.

**Comment by jlasseiceira** [comment]
Hello @aHatakeyama, thank you so much for your fast response, and sorry for my late response.  
I made a mistake in my previous statement, i want to say that the error is in the data version after 2016_06, so in this case the data from 2016_09.  
I do a merge of the two regions of Portugal (prtpt2 and prtpt3) and then use the output data in the Process MultiNet Street Data Tool. But i still get that error, in the latest data from TomTom

**Comment by aHatakeyama** [comment]
Hi @jlasseiceira,

I combined the prtpt2 and prtpt3 regions of the 2016_09 MultiNet data into combined feature classes and tables for nw, mn, mp, si, and sp; and then I ran the Process MultiNet Street Data tool (version 10.4.1.1)  against these combined feature classes and tables -- it also completed successfully after about 20 minutes.

Are you sure that you're combining prtpt2________mn and prtpt3________mn together to make your prtprt________mn common feature class; as well as combining prtpt2________mp and prtpt3________mp together to make your prtprt________mp common table?

**Comment by jlasseiceira** [comment]
hello @aHatakeyama , 
Thank you once again for your help, when i did the merge of prtpt2 ans prtpt3 i did of all the files in the shame modelbuilder. But now i tried just to merge the feature classes and the tables used in the Multinet Street Data Tool, and i got this erro at the end:

Succeeded at Mon Nov 21 16:54:23 2016 (Elapsed Time: 6,69 seconds)
Creating and building the network dataset...
File read/write error occurred.
   at ESRI.ArcGIS.Geodatabase.INetworkBuild.BuildNetwork(IEnvelope areaToBuild)
   at GPProcessVendorDataFunctions.ProcessMultiNetDataFunction.CreateAndBuildNetworkDataset(String outputFileGdbPath, Double fgdbVersion, String fdsName, String ndsName, Boolean createNetworkAttributesInMetric, Boolean createTwoDistanceAttributes, String timeZoneIDBaseFieldName, Boolean directedTimeZoneIDFields, String commonTimeZone, Boolean usesHistoricalTraffic, ITrafficFeedLocation trafficFeedLocation, Boolean usesRSTable, Boolean usesLTRTable, Boolean usesLRSTable, String lrsStatsTableName)
   at GPProcessVendorDataFunctions.ProcessMultiNetDataFunction.Execute(IArray paramvalues, ITrackCancel trackcancel, IGPEnvironmentManager envMgr, IGPMessages messages)
Failed to execute (ProcessMultiNetData).
Failed at Mon Nov 21 17:07:37 2016 (Elapsed Time: 37 minutes 0 seconds)
.

**Comment by aHatakeyama** [comment]
Are you sure you have enough space in your %TEMP% folder?  It helps if you have dozens to hundreds of GB free in your %TEMP% folder.  The %TEMP% folder typically is on the C: drive by default and not necessarily the drive where you're creating the data.

**Comment by jlasseiceira** [comment]
That was indeed the problem, thank you so much for your help. It worked fine now. 
Best Regards
