### ISSUE TITLE
Getting Warning For esriRegasm.exe

### ISSUE THREAD

**Issue by Behseini** [Esri/street-data-processing-tools#7]
Building the Street Data Processing Tools 10.4.1.1 on Vs 2015 I am getting this Warning Message

> The command "esriRegasm.exe"C:\xxxx\xxxx\bin\Debug\GPProcessVendorDataFunctions.dll" / p:Engine /s" exited with code -1.

Can you please let me know what is this and should I be worry about it? Is there any fix for this?

![warning](https://cloud.githubusercontent.com/assets/4685676/21195131/5e668772-c1e7-11e6-8dc0-035faee92520.png)

Thanks

**Comment by aHatakeyama** [comment]
@Behseini, the tool was set to register against both ArcGIS Desktop and ArcEngine when you compile.  If you don't have ArcEngine installed, it will raise that warning when you compile.  However, it still does work against ArcGIS Desktop.  

Actually, the tool really wasn't meant to work against ArcEgnine, so I've removed that registration line in v10.4.1.2.  Thank you very much for reporting this!
