### ISSUE TITLE
Getting Error On Using Tool With HERE NAVSTREETS Data

### ISSUE THREAD

**Issue by BeClevest** [Esri/street-data-processing-tools#8]
We are using the latest version of tool (10.4.1.1) on top of ArcGIS 10.4.1 (built 10.4.4.5686) to process Street data from HERE NAVSTREETS. but after spending couple of hours we are getting this error

> Exception from HRESULT: 0x800422F8
>    at ESRI.ArcGIS.Geodatabase.IDatasetContainer2.CreateDataset(IDEDataset DataElement)
>    at GPProcessVendorDataFunctions.ProcessNavStreetsDataFunction.CreateAndBuildNetworkDataset(String outputFileGdbPath, Double fgdbVersion, String fdsName, String ndsName, Boolean createNetworkAttributesInMetric, Boolean createArcGISOnlineNetworkAttributes, String timeZoneIDBaseFieldName, Boolean directedTimeZoneIDFields, String commonTimeZone, Boolean usesHistoricalTraffic, ITrafficFeedLocation trafficFeedLocation, Boolean usesTransport) in C:\xxx\Master\ProcessNavStreetsDataFunction.cs:line 6997
>    at GPProcessVendorDataFunctions.ProcessNavStreetsDataFunction.Execute(IArray paramvalues, ITrackCancel trackcancel, IGPEnvironmentManager envMgr, IGPMessages messages) in C:\xxx\Master\ProcessNavStreetsDataFunction.cs:line 3146
> Failed to execute (ProcessNavStreetsData).

![2016-12-14_1405](https://cloud.githubusercontent.com/assets/19611313/21203614/1f776f92-c208-11e6-9bb8-6f290ba53371.png)

Basically, I am using the same tool except of disabling two Fields `"EXPR_LANE","CARPOOLRD"` from the `StreetsFieldNames` array and also commenting out 
```
//evalNetAttr = CreateAvoidNetworkAttribute("Avoid Express Lanes", "[EXPR_LANE] = \"Y\"",  true, fgdbVersion, edgeNetworkSource, -1.0);
//attributeArray.Add(evalNetAttr);
//evalNetAttr = CreateAvoidNetworkAttribute("Avoid Carpool Roads", "[CARPOOLRD] = \"Y\"", true, fgdbVersion, edgeNetworkSource, -1.0);
//attributeArray.Add(evalNetAttr);
```
since I was getting these errors when trying to run the tool

> "Field named EXPR_LANE not found"
> "Field named CARPOOLRD not found"

the Errors however refers to:

```
CreateAndBuildNetworkDataset(outputFileGdbPath, fgdbVersion, fdsName, ndsName, createNetworkAttributesInMetric,
                                             createArcGISOnlineNetworkAttributes, timeZoneIDBaseFieldName, directedTimeZoneIDFields, commonTimeZone,
                                             usesHistoricalTraffic, trafficFeedLocation, usesTransport);
```

and

`var networkDataset = (INetworkDataset)datasetContainer2.CreateDataset(deDataset);`

Can you please let me know what causing the issue and how Can I fix this?Thanks

**Comment by aHatakeyama** [comment]
@behClevest,

HRESULT: 0x800422F8 if you convert it to a signed 32-bit integer represents -2147212552.  If you look up this number in the list of fdoError constants at http://desktop.arcgis.com/en/arcobjects/latest/net/webframe.htm#fdoError.htm, you'll see that the error is `FDO_E_NETWORK_TRAVEL_MODE_RESTRICTION_ATTRIBUTE_NOT_FOUND`.

Many of the network attributes created in the tool are also used in travel modes also created in the tool.  Since you're commenting out the creation of these network attributes, you must also comment out the lines that add these network attributes you've excluded to various travel modes.

**Comment by BeClevest** [comment]
Thanks, 
After commenting out all other associated fields from `restrictionsArray` we were able to run the tool successfully

**Comment by aHatakeyama** [comment]
I'm glad to hear that you're now able to get this working.
